# Generated by Django 4.1.5 on 2023-01-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
